// Generated by jextract

package net.renderdoc.api;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$0 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$0() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        MemoryLayout.sequenceLayout(2, JAVA_INT).withName("__val")
    ).withName("");
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(JAVA_INT,
        JAVA_INT,
        JAVA_INT
    );
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(pRENDERDOC_SetCaptureOptionU32.class, "apply", constants$0.const$1);
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        constants$0.const$1
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(JAVA_INT,
        JAVA_INT,
        JAVA_FLOAT
    );
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(pRENDERDOC_SetCaptureOptionF32.class, "apply", constants$0.const$4);
}


