// Generated by jextract

package net.renderdoc.api;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$4 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$4() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(pRENDERDOC_RemoveHooks.class, "apply", constants$3.const$5);
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        constants$3.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(pRENDERDOC_Shutdown.class, "apply", constants$3.const$5);
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(pRENDERDOC_UnloadCrashHandler.class, "apply", constants$3.const$5);
    static final FunctionDescriptor const$4 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(pRENDERDOC_SetCaptureFilePathTemplate.class, "apply", constants$4.const$4);
}


