// Generated by jextract

package net.renderdoc.api;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$8 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$8() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(pRENDERDOC_GetAPIVersion.class, "apply", constants$8.const$0);
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        constants$8.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(pRENDERDOC_ShowReplayUI.class, "apply", constants$2.const$5);
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(pRENDERDOC_SetActiveWindow.class, "apply", constants$6.const$4);
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(pRENDERDOC_TriggerCapture.class, "apply", constants$3.const$5);
}


