// Generated by jextract

package net.renderdoc.api;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$13 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$13() {}
    static final VarHandle const$0 = constants$10.const$4.varHandle(MemoryLayout.PathElement.groupElement("$anon$1"), MemoryLayout.PathElement.groupElement("SetCaptureFilePathTemplate"));
    static final VarHandle const$1 = constants$10.const$4.varHandle(MemoryLayout.PathElement.groupElement("$anon$2"), MemoryLayout.PathElement.groupElement("GetLogFilePathTemplate"));
    static final VarHandle const$2 = constants$10.const$4.varHandle(MemoryLayout.PathElement.groupElement("$anon$2"), MemoryLayout.PathElement.groupElement("GetCaptureFilePathTemplate"));
    static final VarHandle const$3 = constants$10.const$4.varHandle(MemoryLayout.PathElement.groupElement("GetNumCaptures"));
    static final VarHandle const$4 = constants$10.const$4.varHandle(MemoryLayout.PathElement.groupElement("GetCapture"));
    static final VarHandle const$5 = constants$10.const$4.varHandle(MemoryLayout.PathElement.groupElement("TriggerCapture"));
}


