// Generated by jextract

package net.renderdoc.api;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$5 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$5() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        constants$4.const$4
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(RuntimeHelper.POINTER);
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(pRENDERDOC_GetCaptureFilePathTemplate.class, "apply", constants$5.const$1);
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        constants$5.const$1
    );
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(pRENDERDOC_SetLogFilePathTemplate.class, "apply", constants$4.const$4);
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(pRENDERDOC_GetLogFilePathTemplate.class, "apply", constants$5.const$1);
}


