// Generated by jextract

package net.renderdoc.api;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$7 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$7() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        constants$6.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(pRENDERDOC_IsTargetControlConnected.class, "apply", constants$2.const$5);
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(pRENDERDOC_IsRemoteAccessConnected.class, "apply", constants$2.const$5);
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(JAVA_INT,
        JAVA_INT,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(pRENDERDOC_LaunchReplayUI.class, "apply", constants$7.const$3);
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        constants$7.const$3
    );
}


