// Generated by jextract

package net.renderdoc.api;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$15 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$15() {}
    static final VarHandle const$0 = constants$10.const$4.varHandle(MemoryLayout.PathElement.groupElement("EndFrameCapture"));
    static final VarHandle const$1 = constants$10.const$4.varHandle(MemoryLayout.PathElement.groupElement("TriggerMultiFrameCapture"));
    static final VarHandle const$2 = constants$10.const$4.varHandle(MemoryLayout.PathElement.groupElement("SetCaptureFileComments"));
    static final VarHandle const$3 = constants$10.const$4.varHandle(MemoryLayout.PathElement.groupElement("DiscardFrameCapture"));
    static final VarHandle const$4 = constants$10.const$4.varHandle(MemoryLayout.PathElement.groupElement("ShowReplayUI"));
    static final VarHandle const$5 = constants$10.const$4.varHandle(MemoryLayout.PathElement.groupElement("SetCaptureTitle"));
}


