// Generated by jextract

package net.renderdoc.api;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$3 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$3() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(pRENDERDOC_GetOverlayBits.class, "apply", constants$2.const$5);
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        constants$2.const$5
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.ofVoid(
        JAVA_INT,
        JAVA_INT
    );
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(pRENDERDOC_MaskOverlayBits.class, "apply", constants$3.const$2);
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        constants$3.const$2
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.ofVoid();
}


