// Generated by jextract

package net.renderdoc.api;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$11 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$11() {}
    static final VarHandle const$0 = constants$10.const$4.varHandle(MemoryLayout.PathElement.groupElement("SetCaptureOptionU32"));
    static final VarHandle const$1 = constants$10.const$4.varHandle(MemoryLayout.PathElement.groupElement("SetCaptureOptionF32"));
    static final VarHandle const$2 = constants$10.const$4.varHandle(MemoryLayout.PathElement.groupElement("GetCaptureOptionU32"));
    static final VarHandle const$3 = constants$10.const$4.varHandle(MemoryLayout.PathElement.groupElement("GetCaptureOptionF32"));
    static final VarHandle const$4 = constants$10.const$4.varHandle(MemoryLayout.PathElement.groupElement("SetFocusToggleKeys"));
    static final VarHandle const$5 = constants$10.const$4.varHandle(MemoryLayout.PathElement.groupElement("SetCaptureKeys"));
}


