// Generated by jextract

package net.renderdoc.api;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$14 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$14() {}
    static final VarHandle const$0 = constants$10.const$4.varHandle(MemoryLayout.PathElement.groupElement("$anon$3"), MemoryLayout.PathElement.groupElement("IsRemoteAccessConnected"));
    static final VarHandle const$1 = constants$10.const$4.varHandle(MemoryLayout.PathElement.groupElement("$anon$3"), MemoryLayout.PathElement.groupElement("IsTargetControlConnected"));
    static final VarHandle const$2 = constants$10.const$4.varHandle(MemoryLayout.PathElement.groupElement("LaunchReplayUI"));
    static final VarHandle const$3 = constants$10.const$4.varHandle(MemoryLayout.PathElement.groupElement("SetActiveWindow"));
    static final VarHandle const$4 = constants$10.const$4.varHandle(MemoryLayout.PathElement.groupElement("StartFrameCapture"));
    static final VarHandle const$5 = constants$10.const$4.varHandle(MemoryLayout.PathElement.groupElement("IsFrameCapturing"));
}


