// Generated by jextract

package net.renderdoc.api;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef void (*pRENDERDOC_SetFocusToggleKeys)(RENDERDOC_InputButton *, int)
 * }
 */
public final class pRENDERDOC_SetFocusToggleKeys {

    private pRENDERDOC_SetFocusToggleKeys() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        void apply(MemorySegment keys, int num);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
        renderdoc_app_h.C_POINTER,
        renderdoc_app_h.C_INT
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = renderdoc_app_h.upcallHandle(pRENDERDOC_SetFocusToggleKeys.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(pRENDERDOC_SetFocusToggleKeys.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static void invoke(MemorySegment funcPtr, MemorySegment keys, int num) {
        try {
             DOWN$MH.invokeExact(funcPtr, keys, num);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

