// Generated by jextract

package net.renderdoc.api;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * void (*pRENDERDOC_TriggerMultiFrameCapture)(unsigned int numFrames);
 * }
 */
public interface pRENDERDOC_TriggerMultiFrameCapture {

    void apply(int numFrames);
    static MemorySegment allocate(pRENDERDOC_TriggerMultiFrameCapture fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$9.const$1, fi, constants$9.const$0, scope);
    }
    static pRENDERDOC_TriggerMultiFrameCapture ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (int _numFrames) -> {
            try {
                constants$9.const$2.invokeExact(symbol, _numFrames);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


