// Generated by jextract

package net.renderdoc.api;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * void (*pRENDERDOC_SetActiveWindow)(void* device,void* wndHandle);
 * }
 */
public interface pRENDERDOC_SetActiveWindow {

    void apply(java.lang.foreign.MemorySegment device, java.lang.foreign.MemorySegment wndHandle);
    static MemorySegment allocate(pRENDERDOC_SetActiveWindow fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$8.const$4, fi, constants$6.const$4, scope);
    }
    static pRENDERDOC_SetActiveWindow ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment _device, java.lang.foreign.MemorySegment _wndHandle) -> {
            try {
                constants$7.const$0.invokeExact(symbol, _device, _wndHandle);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


