// Generated by jextract

package net.renderdoc.api;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * void (*pRENDERDOC_SetCaptureFilePathTemplate)(char* pathtemplate);
 * }
 */
public interface pRENDERDOC_SetCaptureFilePathTemplate {

    void apply(java.lang.foreign.MemorySegment title);
    static MemorySegment allocate(pRENDERDOC_SetCaptureFilePathTemplate fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$4.const$5, fi, constants$4.const$4, scope);
    }
    static pRENDERDOC_SetCaptureFilePathTemplate ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment _title) -> {
            try {
                constants$5.const$0.invokeExact(symbol, _title);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


