// Generated by jextract

package net.renderdoc.api;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef uint32_t (*pRENDERDOC_LaunchReplayUI)(uint32_t, const char *)
 * }
 */
public final class pRENDERDOC_LaunchReplayUI {

    private pRENDERDOC_LaunchReplayUI() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        int apply(int connectTargetControl, MemorySegment cmdline);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
        renderdoc_app_h.C_INT,
        renderdoc_app_h.C_INT,
        renderdoc_app_h.C_POINTER
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = renderdoc_app_h.upcallHandle(pRENDERDOC_LaunchReplayUI.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(pRENDERDOC_LaunchReplayUI.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static int invoke(MemorySegment funcPtr, int connectTargetControl, MemorySegment cmdline) {
        try {
            return (int) DOWN$MH.invokeExact(funcPtr, connectTargetControl, cmdline);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

