// Generated by jextract

package net.renderdoc.api;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef float (*pRENDERDOC_GetCaptureOptionF32)(RENDERDOC_CaptureOption)
 * }
 */
public final class pRENDERDOC_GetCaptureOptionF32 {

    private pRENDERDOC_GetCaptureOptionF32() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        float apply(int opt);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
        renderdoc_app_h.C_FLOAT,
        renderdoc_app_h.C_INT
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = renderdoc_app_h.upcallHandle(pRENDERDOC_GetCaptureOptionF32.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(pRENDERDOC_GetCaptureOptionF32.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static float invoke(MemorySegment funcPtr, int opt) {
        try {
            return (float) DOWN$MH.invokeExact(funcPtr, opt);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

