// Generated by jextract

package net.renderdoc.api;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class renderdoc_app_h  {

    public static final OfByte C_CHAR = JAVA_BYTE;
    public static final OfShort C_SHORT = JAVA_SHORT;
    public static final OfInt C_INT = JAVA_INT;
    public static final OfLong C_LONG = JAVA_LONG;
    public static final OfLong C_LONG_LONG = JAVA_LONG;
    public static final OfFloat C_FLOAT = JAVA_FLOAT;
    public static final OfDouble C_DOUBLE = JAVA_DOUBLE;
    public static final AddressLayout C_POINTER = RuntimeHelper.POINTER;
    /**
     * {@snippet :
     * #define _STDINT_H 1
     * }
     */
    public static int _STDINT_H() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define _FEATURES_H 1
     * }
     */
    public static int _FEATURES_H() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define _DEFAULT_SOURCE 1
     * }
     */
    public static int _DEFAULT_SOURCE() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define __GLIBC_USE_ISOC2X 0
     * }
     */
    public static int __GLIBC_USE_ISOC2X() {
        return (int)0L;
    }
    /**
     * {@snippet :
     * #define __USE_ISOC11 1
     * }
     */
    public static int __USE_ISOC11() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define __USE_ISOC99 1
     * }
     */
    public static int __USE_ISOC99() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define __USE_ISOC95 1
     * }
     */
    public static int __USE_ISOC95() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define __USE_POSIX_IMPLICITLY 1
     * }
     */
    public static int __USE_POSIX_IMPLICITLY() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define _POSIX_SOURCE 1
     * }
     */
    public static int _POSIX_SOURCE() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define __USE_POSIX 1
     * }
     */
    public static int __USE_POSIX() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define __USE_POSIX2 1
     * }
     */
    public static int __USE_POSIX2() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define __USE_POSIX199309 1
     * }
     */
    public static int __USE_POSIX199309() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define __USE_POSIX199506 1
     * }
     */
    public static int __USE_POSIX199506() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define __USE_XOPEN2K 1
     * }
     */
    public static int __USE_XOPEN2K() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define __USE_XOPEN2K8 1
     * }
     */
    public static int __USE_XOPEN2K8() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define _ATFILE_SOURCE 1
     * }
     */
    public static int _ATFILE_SOURCE() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define __WORDSIZE 64
     * }
     */
    public static int __WORDSIZE() {
        return (int)64L;
    }
    /**
     * {@snippet :
     * #define __WORDSIZE_TIME64_COMPAT32 1
     * }
     */
    public static int __WORDSIZE_TIME64_COMPAT32() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define __SYSCALL_WORDSIZE 64
     * }
     */
    public static int __SYSCALL_WORDSIZE() {
        return (int)64L;
    }
    /**
     * {@snippet :
     * #define __USE_TIME_BITS64 1
     * }
     */
    public static int __USE_TIME_BITS64() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define __USE_MISC 1
     * }
     */
    public static int __USE_MISC() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define __USE_ATFILE 1
     * }
     */
    public static int __USE_ATFILE() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define __USE_FORTIFY_LEVEL 0
     * }
     */
    public static int __USE_FORTIFY_LEVEL() {
        return (int)0L;
    }
    /**
     * {@snippet :
     * #define __GLIBC_USE_DEPRECATED_GETS 0
     * }
     */
    public static int __GLIBC_USE_DEPRECATED_GETS() {
        return (int)0L;
    }
    /**
     * {@snippet :
     * #define __GLIBC_USE_DEPRECATED_SCANF 0
     * }
     */
    public static int __GLIBC_USE_DEPRECATED_SCANF() {
        return (int)0L;
    }
    /**
     * {@snippet :
     * #define __GLIBC_USE_C2X_STRTOL 0
     * }
     */
    public static int __GLIBC_USE_C2X_STRTOL() {
        return (int)0L;
    }
    /**
     * {@snippet :
     * #define _STDC_PREDEF_H 1
     * }
     */
    public static int _STDC_PREDEF_H() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define __STDC_IEC_559__ 1
     * }
     */
    public static int __STDC_IEC_559__() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define __STDC_IEC_559_COMPLEX__ 1
     * }
     */
    public static int __STDC_IEC_559_COMPLEX__() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define __GNU_LIBRARY__ 6
     * }
     */
    public static int __GNU_LIBRARY__() {
        return (int)6L;
    }
    /**
     * {@snippet :
     * #define __GLIBC__ 2
     * }
     */
    public static int __GLIBC__() {
        return (int)2L;
    }
    /**
     * {@snippet :
     * #define __GLIBC_MINOR__ 39
     * }
     */
    public static int __GLIBC_MINOR__() {
        return (int)39L;
    }
    /**
     * {@snippet :
     * #define _SYS_CDEFS_H 1
     * }
     */
    public static int _SYS_CDEFS_H() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define __glibc_c99_flexarr_available 1
     * }
     */
    public static int __glibc_c99_flexarr_available() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define __LDOUBLE_REDIRECTS_TO_FLOAT128_ABI 0
     * }
     */
    public static int __LDOUBLE_REDIRECTS_TO_FLOAT128_ABI() {
        return (int)0L;
    }
    /**
     * {@snippet :
     * #define __HAVE_GENERIC_SELECTION 1
     * }
     */
    public static int __HAVE_GENERIC_SELECTION() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define __GLIBC_USE_LIB_EXT2 0
     * }
     */
    public static int __GLIBC_USE_LIB_EXT2() {
        return (int)0L;
    }
    /**
     * {@snippet :
     * #define __GLIBC_USE_IEC_60559_BFP_EXT 0
     * }
     */
    public static int __GLIBC_USE_IEC_60559_BFP_EXT() {
        return (int)0L;
    }
    /**
     * {@snippet :
     * #define __GLIBC_USE_IEC_60559_BFP_EXT_C2X 0
     * }
     */
    public static int __GLIBC_USE_IEC_60559_BFP_EXT_C2X() {
        return (int)0L;
    }
    /**
     * {@snippet :
     * #define __GLIBC_USE_IEC_60559_EXT 0
     * }
     */
    public static int __GLIBC_USE_IEC_60559_EXT() {
        return (int)0L;
    }
    /**
     * {@snippet :
     * #define __GLIBC_USE_IEC_60559_FUNCS_EXT 0
     * }
     */
    public static int __GLIBC_USE_IEC_60559_FUNCS_EXT() {
        return (int)0L;
    }
    /**
     * {@snippet :
     * #define __GLIBC_USE_IEC_60559_FUNCS_EXT_C2X 0
     * }
     */
    public static int __GLIBC_USE_IEC_60559_FUNCS_EXT_C2X() {
        return (int)0L;
    }
    /**
     * {@snippet :
     * #define __GLIBC_USE_IEC_60559_TYPES_EXT 0
     * }
     */
    public static int __GLIBC_USE_IEC_60559_TYPES_EXT() {
        return (int)0L;
    }
    /**
     * {@snippet :
     * #define _BITS_TYPES_H 1
     * }
     */
    public static int _BITS_TYPES_H() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define _BITS_TYPESIZES_H 1
     * }
     */
    public static int _BITS_TYPESIZES_H() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define __OFF_T_MATCHES_OFF64_T 1
     * }
     */
    public static int __OFF_T_MATCHES_OFF64_T() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define __INO_T_MATCHES_INO64_T 1
     * }
     */
    public static int __INO_T_MATCHES_INO64_T() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define __RLIM_T_MATCHES_RLIM64_T 1
     * }
     */
    public static int __RLIM_T_MATCHES_RLIM64_T() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define __STATFS_MATCHES_STATFS64 1
     * }
     */
    public static int __STATFS_MATCHES_STATFS64() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define __KERNEL_OLD_TIMEVAL_MATCHES_TIMEVAL64 1
     * }
     */
    public static int __KERNEL_OLD_TIMEVAL_MATCHES_TIMEVAL64() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define __FD_SETSIZE 1024
     * }
     */
    public static int __FD_SETSIZE() {
        return (int)1024L;
    }
    /**
     * {@snippet :
     * #define _BITS_TIME64_H 1
     * }
     */
    public static int _BITS_TIME64_H() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define _BITS_WCHAR_H 1
     * }
     */
    public static int _BITS_WCHAR_H() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define _BITS_STDINT_INTN_H 1
     * }
     */
    public static int _BITS_STDINT_INTN_H() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define _BITS_STDINT_UINTN_H 1
     * }
     */
    public static int _BITS_STDINT_UINTN_H() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define _BITS_STDINT_LEAST_H 1
     * }
     */
    public static int _BITS_STDINT_LEAST_H() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * typedef unsigned char __u_char;
     * }
     */
    public static final OfByte __u_char = JAVA_BYTE;
    /**
     * {@snippet :
     * typedef unsigned short __u_short;
     * }
     */
    public static final OfShort __u_short = JAVA_SHORT;
    /**
     * {@snippet :
     * typedef unsigned int __u_int;
     * }
     */
    public static final OfInt __u_int = JAVA_INT;
    /**
     * {@snippet :
     * typedef unsigned long __u_long;
     * }
     */
    public static final OfLong __u_long = JAVA_LONG;
    /**
     * {@snippet :
     * typedef signed char __int8_t;
     * }
     */
    public static final OfByte __int8_t = JAVA_BYTE;
    /**
     * {@snippet :
     * typedef unsigned char __uint8_t;
     * }
     */
    public static final OfByte __uint8_t = JAVA_BYTE;
    /**
     * {@snippet :
     * typedef short __int16_t;
     * }
     */
    public static final OfShort __int16_t = JAVA_SHORT;
    /**
     * {@snippet :
     * typedef unsigned short __uint16_t;
     * }
     */
    public static final OfShort __uint16_t = JAVA_SHORT;
    /**
     * {@snippet :
     * typedef int __int32_t;
     * }
     */
    public static final OfInt __int32_t = JAVA_INT;
    /**
     * {@snippet :
     * typedef unsigned int __uint32_t;
     * }
     */
    public static final OfInt __uint32_t = JAVA_INT;
    /**
     * {@snippet :
     * typedef long __int64_t;
     * }
     */
    public static final OfLong __int64_t = JAVA_LONG;
    /**
     * {@snippet :
     * typedef unsigned long __uint64_t;
     * }
     */
    public static final OfLong __uint64_t = JAVA_LONG;
    /**
     * {@snippet :
     * typedef signed char __int_least8_t;
     * }
     */
    public static final OfByte __int_least8_t = JAVA_BYTE;
    /**
     * {@snippet :
     * typedef unsigned char __uint_least8_t;
     * }
     */
    public static final OfByte __uint_least8_t = JAVA_BYTE;
    /**
     * {@snippet :
     * typedef short __int_least16_t;
     * }
     */
    public static final OfShort __int_least16_t = JAVA_SHORT;
    /**
     * {@snippet :
     * typedef unsigned short __uint_least16_t;
     * }
     */
    public static final OfShort __uint_least16_t = JAVA_SHORT;
    /**
     * {@snippet :
     * typedef int __int_least32_t;
     * }
     */
    public static final OfInt __int_least32_t = JAVA_INT;
    /**
     * {@snippet :
     * typedef unsigned int __uint_least32_t;
     * }
     */
    public static final OfInt __uint_least32_t = JAVA_INT;
    /**
     * {@snippet :
     * typedef long __int_least64_t;
     * }
     */
    public static final OfLong __int_least64_t = JAVA_LONG;
    /**
     * {@snippet :
     * typedef unsigned long __uint_least64_t;
     * }
     */
    public static final OfLong __uint_least64_t = JAVA_LONG;
    /**
     * {@snippet :
     * typedef long __quad_t;
     * }
     */
    public static final OfLong __quad_t = JAVA_LONG;
    /**
     * {@snippet :
     * typedef unsigned long __u_quad_t;
     * }
     */
    public static final OfLong __u_quad_t = JAVA_LONG;
    /**
     * {@snippet :
     * typedef long __intmax_t;
     * }
     */
    public static final OfLong __intmax_t = JAVA_LONG;
    /**
     * {@snippet :
     * typedef unsigned long __uintmax_t;
     * }
     */
    public static final OfLong __uintmax_t = JAVA_LONG;
    /**
     * {@snippet :
     * typedef unsigned long __dev_t;
     * }
     */
    public static final OfLong __dev_t = JAVA_LONG;
    /**
     * {@snippet :
     * typedef unsigned int __uid_t;
     * }
     */
    public static final OfInt __uid_t = JAVA_INT;
    /**
     * {@snippet :
     * typedef unsigned int __gid_t;
     * }
     */
    public static final OfInt __gid_t = JAVA_INT;
    /**
     * {@snippet :
     * typedef unsigned long __ino_t;
     * }
     */
    public static final OfLong __ino_t = JAVA_LONG;
    /**
     * {@snippet :
     * typedef unsigned long __ino64_t;
     * }
     */
    public static final OfLong __ino64_t = JAVA_LONG;
    /**
     * {@snippet :
     * typedef unsigned int __mode_t;
     * }
     */
    public static final OfInt __mode_t = JAVA_INT;
    /**
     * {@snippet :
     * typedef unsigned long __nlink_t;
     * }
     */
    public static final OfLong __nlink_t = JAVA_LONG;
    /**
     * {@snippet :
     * typedef long __off_t;
     * }
     */
    public static final OfLong __off_t = JAVA_LONG;
    /**
     * {@snippet :
     * typedef long __off64_t;
     * }
     */
    public static final OfLong __off64_t = JAVA_LONG;
    /**
     * {@snippet :
     * typedef int __pid_t;
     * }
     */
    public static final OfInt __pid_t = JAVA_INT;
    /**
     * {@snippet :
     * typedef long __clock_t;
     * }
     */
    public static final OfLong __clock_t = JAVA_LONG;
    /**
     * {@snippet :
     * typedef unsigned long __rlim_t;
     * }
     */
    public static final OfLong __rlim_t = JAVA_LONG;
    /**
     * {@snippet :
     * typedef unsigned long __rlim64_t;
     * }
     */
    public static final OfLong __rlim64_t = JAVA_LONG;
    /**
     * {@snippet :
     * typedef unsigned int __id_t;
     * }
     */
    public static final OfInt __id_t = JAVA_INT;
    /**
     * {@snippet :
     * typedef long __time_t;
     * }
     */
    public static final OfLong __time_t = JAVA_LONG;
    /**
     * {@snippet :
     * typedef unsigned int __useconds_t;
     * }
     */
    public static final OfInt __useconds_t = JAVA_INT;
    /**
     * {@snippet :
     * typedef long __suseconds_t;
     * }
     */
    public static final OfLong __suseconds_t = JAVA_LONG;
    /**
     * {@snippet :
     * typedef long __suseconds64_t;
     * }
     */
    public static final OfLong __suseconds64_t = JAVA_LONG;
    /**
     * {@snippet :
     * typedef int __daddr_t;
     * }
     */
    public static final OfInt __daddr_t = JAVA_INT;
    /**
     * {@snippet :
     * typedef int __key_t;
     * }
     */
    public static final OfInt __key_t = JAVA_INT;
    /**
     * {@snippet :
     * typedef int __clockid_t;
     * }
     */
    public static final OfInt __clockid_t = JAVA_INT;
    /**
     * {@snippet :
     * typedef void* __timer_t;
     * }
     */
    public static final AddressLayout __timer_t = RuntimeHelper.POINTER;
    /**
     * {@snippet :
     * typedef long __blksize_t;
     * }
     */
    public static final OfLong __blksize_t = JAVA_LONG;
    /**
     * {@snippet :
     * typedef long __blkcnt_t;
     * }
     */
    public static final OfLong __blkcnt_t = JAVA_LONG;
    /**
     * {@snippet :
     * typedef long __blkcnt64_t;
     * }
     */
    public static final OfLong __blkcnt64_t = JAVA_LONG;
    /**
     * {@snippet :
     * typedef unsigned long __fsblkcnt_t;
     * }
     */
    public static final OfLong __fsblkcnt_t = JAVA_LONG;
    /**
     * {@snippet :
     * typedef unsigned long __fsblkcnt64_t;
     * }
     */
    public static final OfLong __fsblkcnt64_t = JAVA_LONG;
    /**
     * {@snippet :
     * typedef unsigned long __fsfilcnt_t;
     * }
     */
    public static final OfLong __fsfilcnt_t = JAVA_LONG;
    /**
     * {@snippet :
     * typedef unsigned long __fsfilcnt64_t;
     * }
     */
    public static final OfLong __fsfilcnt64_t = JAVA_LONG;
    /**
     * {@snippet :
     * typedef long __fsword_t;
     * }
     */
    public static final OfLong __fsword_t = JAVA_LONG;
    /**
     * {@snippet :
     * typedef long __ssize_t;
     * }
     */
    public static final OfLong __ssize_t = JAVA_LONG;
    /**
     * {@snippet :
     * typedef long __syscall_slong_t;
     * }
     */
    public static final OfLong __syscall_slong_t = JAVA_LONG;
    /**
     * {@snippet :
     * typedef unsigned long __syscall_ulong_t;
     * }
     */
    public static final OfLong __syscall_ulong_t = JAVA_LONG;
    /**
     * {@snippet :
     * typedef long __loff_t;
     * }
     */
    public static final OfLong __loff_t = JAVA_LONG;
    /**
     * {@snippet :
     * typedef char* __caddr_t;
     * }
     */
    public static final AddressLayout __caddr_t = RuntimeHelper.POINTER;
    /**
     * {@snippet :
     * typedef long __intptr_t;
     * }
     */
    public static final OfLong __intptr_t = JAVA_LONG;
    /**
     * {@snippet :
     * typedef unsigned int __socklen_t;
     * }
     */
    public static final OfInt __socklen_t = JAVA_INT;
    /**
     * {@snippet :
     * typedef int __sig_atomic_t;
     * }
     */
    public static final OfInt __sig_atomic_t = JAVA_INT;
    /**
     * {@snippet :
     * typedef signed char int8_t;
     * }
     */
    public static final OfByte int8_t = JAVA_BYTE;
    /**
     * {@snippet :
     * typedef short int16_t;
     * }
     */
    public static final OfShort int16_t = JAVA_SHORT;
    /**
     * {@snippet :
     * typedef int int32_t;
     * }
     */
    public static final OfInt int32_t = JAVA_INT;
    /**
     * {@snippet :
     * typedef long int64_t;
     * }
     */
    public static final OfLong int64_t = JAVA_LONG;
    /**
     * {@snippet :
     * typedef unsigned char uint8_t;
     * }
     */
    public static final OfByte uint8_t = JAVA_BYTE;
    /**
     * {@snippet :
     * typedef unsigned short uint16_t;
     * }
     */
    public static final OfShort uint16_t = JAVA_SHORT;
    /**
     * {@snippet :
     * typedef unsigned int uint32_t;
     * }
     */
    public static final OfInt uint32_t = JAVA_INT;
    /**
     * {@snippet :
     * typedef unsigned long uint64_t;
     * }
     */
    public static final OfLong uint64_t = JAVA_LONG;
    /**
     * {@snippet :
     * typedef signed char int_least8_t;
     * }
     */
    public static final OfByte int_least8_t = JAVA_BYTE;
    /**
     * {@snippet :
     * typedef short int_least16_t;
     * }
     */
    public static final OfShort int_least16_t = JAVA_SHORT;
    /**
     * {@snippet :
     * typedef int int_least32_t;
     * }
     */
    public static final OfInt int_least32_t = JAVA_INT;
    /**
     * {@snippet :
     * typedef long int_least64_t;
     * }
     */
    public static final OfLong int_least64_t = JAVA_LONG;
    /**
     * {@snippet :
     * typedef unsigned char uint_least8_t;
     * }
     */
    public static final OfByte uint_least8_t = JAVA_BYTE;
    /**
     * {@snippet :
     * typedef unsigned short uint_least16_t;
     * }
     */
    public static final OfShort uint_least16_t = JAVA_SHORT;
    /**
     * {@snippet :
     * typedef unsigned int uint_least32_t;
     * }
     */
    public static final OfInt uint_least32_t = JAVA_INT;
    /**
     * {@snippet :
     * typedef unsigned long uint_least64_t;
     * }
     */
    public static final OfLong uint_least64_t = JAVA_LONG;
    /**
     * {@snippet :
     * typedef signed char int_fast8_t;
     * }
     */
    public static final OfByte int_fast8_t = JAVA_BYTE;
    /**
     * {@snippet :
     * typedef long int_fast16_t;
     * }
     */
    public static final OfLong int_fast16_t = JAVA_LONG;
    /**
     * {@snippet :
     * typedef long int_fast32_t;
     * }
     */
    public static final OfLong int_fast32_t = JAVA_LONG;
    /**
     * {@snippet :
     * typedef long int_fast64_t;
     * }
     */
    public static final OfLong int_fast64_t = JAVA_LONG;
    /**
     * {@snippet :
     * typedef unsigned char uint_fast8_t;
     * }
     */
    public static final OfByte uint_fast8_t = JAVA_BYTE;
    /**
     * {@snippet :
     * typedef unsigned long uint_fast16_t;
     * }
     */
    public static final OfLong uint_fast16_t = JAVA_LONG;
    /**
     * {@snippet :
     * typedef unsigned long uint_fast32_t;
     * }
     */
    public static final OfLong uint_fast32_t = JAVA_LONG;
    /**
     * {@snippet :
     * typedef unsigned long uint_fast64_t;
     * }
     */
    public static final OfLong uint_fast64_t = JAVA_LONG;
    /**
     * {@snippet :
     * typedef long intptr_t;
     * }
     */
    public static final OfLong intptr_t = JAVA_LONG;
    /**
     * {@snippet :
     * typedef unsigned long uintptr_t;
     * }
     */
    public static final OfLong uintptr_t = JAVA_LONG;
    /**
     * {@snippet :
     * typedef long intmax_t;
     * }
     */
    public static final OfLong intmax_t = JAVA_LONG;
    /**
     * {@snippet :
     * typedef unsigned long uintmax_t;
     * }
     */
    public static final OfLong uintmax_t = JAVA_LONG;
    /**
     * {@snippet :
     * enum RENDERDOC_CaptureOption.eRENDERDOC_Option_AllowVSync = 0;
     * }
     */
    public static int eRENDERDOC_Option_AllowVSync() {
        return (int)0L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_CaptureOption.eRENDERDOC_Option_AllowFullscreen = 1;
     * }
     */
    public static int eRENDERDOC_Option_AllowFullscreen() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_CaptureOption.eRENDERDOC_Option_APIValidation = 2;
     * }
     */
    public static int eRENDERDOC_Option_APIValidation() {
        return (int)2L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_CaptureOption.eRENDERDOC_Option_DebugDeviceMode = 2;
     * }
     */
    public static int eRENDERDOC_Option_DebugDeviceMode() {
        return (int)2L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_CaptureOption.eRENDERDOC_Option_CaptureCallstacks = 3;
     * }
     */
    public static int eRENDERDOC_Option_CaptureCallstacks() {
        return (int)3L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_CaptureOption.eRENDERDOC_Option_CaptureCallstacksOnlyDraws = 4;
     * }
     */
    public static int eRENDERDOC_Option_CaptureCallstacksOnlyDraws() {
        return (int)4L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_CaptureOption.eRENDERDOC_Option_CaptureCallstacksOnlyActions = 4;
     * }
     */
    public static int eRENDERDOC_Option_CaptureCallstacksOnlyActions() {
        return (int)4L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_CaptureOption.eRENDERDOC_Option_DelayForDebugger = 5;
     * }
     */
    public static int eRENDERDOC_Option_DelayForDebugger() {
        return (int)5L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_CaptureOption.eRENDERDOC_Option_VerifyBufferAccess = 6;
     * }
     */
    public static int eRENDERDOC_Option_VerifyBufferAccess() {
        return (int)6L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_CaptureOption.eRENDERDOC_Option_VerifyMapWrites = 6;
     * }
     */
    public static int eRENDERDOC_Option_VerifyMapWrites() {
        return (int)6L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_CaptureOption.eRENDERDOC_Option_HookIntoChildren = 7;
     * }
     */
    public static int eRENDERDOC_Option_HookIntoChildren() {
        return (int)7L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_CaptureOption.eRENDERDOC_Option_RefAllResources = 8;
     * }
     */
    public static int eRENDERDOC_Option_RefAllResources() {
        return (int)8L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_CaptureOption.eRENDERDOC_Option_SaveAllInitials = 9;
     * }
     */
    public static int eRENDERDOC_Option_SaveAllInitials() {
        return (int)9L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_CaptureOption.eRENDERDOC_Option_CaptureAllCmdLists = 10;
     * }
     */
    public static int eRENDERDOC_Option_CaptureAllCmdLists() {
        return (int)10L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_CaptureOption.eRENDERDOC_Option_DebugOutputMute = 11;
     * }
     */
    public static int eRENDERDOC_Option_DebugOutputMute() {
        return (int)11L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_CaptureOption.eRENDERDOC_Option_AllowUnsupportedVendorExtensions = 12;
     * }
     */
    public static int eRENDERDOC_Option_AllowUnsupportedVendorExtensions() {
        return (int)12L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_CaptureOption.eRENDERDOC_Option_SoftMemoryLimit = 13;
     * }
     */
    public static int eRENDERDOC_Option_SoftMemoryLimit() {
        return (int)13L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_InputButton.eRENDERDOC_Key_0 = 48;
     * }
     */
    public static int eRENDERDOC_Key_0() {
        return (int)48L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_InputButton.eRENDERDOC_Key_1 = 49;
     * }
     */
    public static int eRENDERDOC_Key_1() {
        return (int)49L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_InputButton.eRENDERDOC_Key_2 = 50;
     * }
     */
    public static int eRENDERDOC_Key_2() {
        return (int)50L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_InputButton.eRENDERDOC_Key_3 = 51;
     * }
     */
    public static int eRENDERDOC_Key_3() {
        return (int)51L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_InputButton.eRENDERDOC_Key_4 = 52;
     * }
     */
    public static int eRENDERDOC_Key_4() {
        return (int)52L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_InputButton.eRENDERDOC_Key_5 = 53;
     * }
     */
    public static int eRENDERDOC_Key_5() {
        return (int)53L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_InputButton.eRENDERDOC_Key_6 = 54;
     * }
     */
    public static int eRENDERDOC_Key_6() {
        return (int)54L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_InputButton.eRENDERDOC_Key_7 = 55;
     * }
     */
    public static int eRENDERDOC_Key_7() {
        return (int)55L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_InputButton.eRENDERDOC_Key_8 = 56;
     * }
     */
    public static int eRENDERDOC_Key_8() {
        return (int)56L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_InputButton.eRENDERDOC_Key_9 = 57;
     * }
     */
    public static int eRENDERDOC_Key_9() {
        return (int)57L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_InputButton.eRENDERDOC_Key_A = 65;
     * }
     */
    public static int eRENDERDOC_Key_A() {
        return (int)65L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_InputButton.eRENDERDOC_Key_B = 66;
     * }
     */
    public static int eRENDERDOC_Key_B() {
        return (int)66L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_InputButton.eRENDERDOC_Key_C = 67;
     * }
     */
    public static int eRENDERDOC_Key_C() {
        return (int)67L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_InputButton.eRENDERDOC_Key_D = 68;
     * }
     */
    public static int eRENDERDOC_Key_D() {
        return (int)68L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_InputButton.eRENDERDOC_Key_E = 69;
     * }
     */
    public static int eRENDERDOC_Key_E() {
        return (int)69L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_InputButton.eRENDERDOC_Key_F = 70;
     * }
     */
    public static int eRENDERDOC_Key_F() {
        return (int)70L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_InputButton.eRENDERDOC_Key_G = 71;
     * }
     */
    public static int eRENDERDOC_Key_G() {
        return (int)71L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_InputButton.eRENDERDOC_Key_H = 72;
     * }
     */
    public static int eRENDERDOC_Key_H() {
        return (int)72L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_InputButton.eRENDERDOC_Key_I = 73;
     * }
     */
    public static int eRENDERDOC_Key_I() {
        return (int)73L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_InputButton.eRENDERDOC_Key_J = 74;
     * }
     */
    public static int eRENDERDOC_Key_J() {
        return (int)74L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_InputButton.eRENDERDOC_Key_K = 75;
     * }
     */
    public static int eRENDERDOC_Key_K() {
        return (int)75L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_InputButton.eRENDERDOC_Key_L = 76;
     * }
     */
    public static int eRENDERDOC_Key_L() {
        return (int)76L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_InputButton.eRENDERDOC_Key_M = 77;
     * }
     */
    public static int eRENDERDOC_Key_M() {
        return (int)77L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_InputButton.eRENDERDOC_Key_N = 78;
     * }
     */
    public static int eRENDERDOC_Key_N() {
        return (int)78L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_InputButton.eRENDERDOC_Key_O = 79;
     * }
     */
    public static int eRENDERDOC_Key_O() {
        return (int)79L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_InputButton.eRENDERDOC_Key_P = 80;
     * }
     */
    public static int eRENDERDOC_Key_P() {
        return (int)80L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_InputButton.eRENDERDOC_Key_Q = 81;
     * }
     */
    public static int eRENDERDOC_Key_Q() {
        return (int)81L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_InputButton.eRENDERDOC_Key_R = 82;
     * }
     */
    public static int eRENDERDOC_Key_R() {
        return (int)82L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_InputButton.eRENDERDOC_Key_S = 83;
     * }
     */
    public static int eRENDERDOC_Key_S() {
        return (int)83L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_InputButton.eRENDERDOC_Key_T = 84;
     * }
     */
    public static int eRENDERDOC_Key_T() {
        return (int)84L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_InputButton.eRENDERDOC_Key_U = 85;
     * }
     */
    public static int eRENDERDOC_Key_U() {
        return (int)85L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_InputButton.eRENDERDOC_Key_V = 86;
     * }
     */
    public static int eRENDERDOC_Key_V() {
        return (int)86L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_InputButton.eRENDERDOC_Key_W = 87;
     * }
     */
    public static int eRENDERDOC_Key_W() {
        return (int)87L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_InputButton.eRENDERDOC_Key_X = 88;
     * }
     */
    public static int eRENDERDOC_Key_X() {
        return (int)88L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_InputButton.eRENDERDOC_Key_Y = 89;
     * }
     */
    public static int eRENDERDOC_Key_Y() {
        return (int)89L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_InputButton.eRENDERDOC_Key_Z = 90;
     * }
     */
    public static int eRENDERDOC_Key_Z() {
        return (int)90L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_InputButton.eRENDERDOC_Key_NonPrintable = 256;
     * }
     */
    public static int eRENDERDOC_Key_NonPrintable() {
        return (int)256L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_InputButton.eRENDERDOC_Key_Divide = 257;
     * }
     */
    public static int eRENDERDOC_Key_Divide() {
        return (int)257L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_InputButton.eRENDERDOC_Key_Multiply = 258;
     * }
     */
    public static int eRENDERDOC_Key_Multiply() {
        return (int)258L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_InputButton.eRENDERDOC_Key_Subtract = 259;
     * }
     */
    public static int eRENDERDOC_Key_Subtract() {
        return (int)259L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_InputButton.eRENDERDOC_Key_Plus = 260;
     * }
     */
    public static int eRENDERDOC_Key_Plus() {
        return (int)260L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_InputButton.eRENDERDOC_Key_F1 = 261;
     * }
     */
    public static int eRENDERDOC_Key_F1() {
        return (int)261L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_InputButton.eRENDERDOC_Key_F2 = 262;
     * }
     */
    public static int eRENDERDOC_Key_F2() {
        return (int)262L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_InputButton.eRENDERDOC_Key_F3 = 263;
     * }
     */
    public static int eRENDERDOC_Key_F3() {
        return (int)263L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_InputButton.eRENDERDOC_Key_F4 = 264;
     * }
     */
    public static int eRENDERDOC_Key_F4() {
        return (int)264L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_InputButton.eRENDERDOC_Key_F5 = 265;
     * }
     */
    public static int eRENDERDOC_Key_F5() {
        return (int)265L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_InputButton.eRENDERDOC_Key_F6 = 266;
     * }
     */
    public static int eRENDERDOC_Key_F6() {
        return (int)266L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_InputButton.eRENDERDOC_Key_F7 = 267;
     * }
     */
    public static int eRENDERDOC_Key_F7() {
        return (int)267L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_InputButton.eRENDERDOC_Key_F8 = 268;
     * }
     */
    public static int eRENDERDOC_Key_F8() {
        return (int)268L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_InputButton.eRENDERDOC_Key_F9 = 269;
     * }
     */
    public static int eRENDERDOC_Key_F9() {
        return (int)269L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_InputButton.eRENDERDOC_Key_F10 = 270;
     * }
     */
    public static int eRENDERDOC_Key_F10() {
        return (int)270L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_InputButton.eRENDERDOC_Key_F11 = 271;
     * }
     */
    public static int eRENDERDOC_Key_F11() {
        return (int)271L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_InputButton.eRENDERDOC_Key_F12 = 272;
     * }
     */
    public static int eRENDERDOC_Key_F12() {
        return (int)272L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_InputButton.eRENDERDOC_Key_Home = 273;
     * }
     */
    public static int eRENDERDOC_Key_Home() {
        return (int)273L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_InputButton.eRENDERDOC_Key_End = 274;
     * }
     */
    public static int eRENDERDOC_Key_End() {
        return (int)274L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_InputButton.eRENDERDOC_Key_Insert = 275;
     * }
     */
    public static int eRENDERDOC_Key_Insert() {
        return (int)275L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_InputButton.eRENDERDOC_Key_Delete = 276;
     * }
     */
    public static int eRENDERDOC_Key_Delete() {
        return (int)276L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_InputButton.eRENDERDOC_Key_PageUp = 277;
     * }
     */
    public static int eRENDERDOC_Key_PageUp() {
        return (int)277L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_InputButton.eRENDERDOC_Key_PageDn = 278;
     * }
     */
    public static int eRENDERDOC_Key_PageDn() {
        return (int)278L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_InputButton.eRENDERDOC_Key_Backspace = 279;
     * }
     */
    public static int eRENDERDOC_Key_Backspace() {
        return (int)279L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_InputButton.eRENDERDOC_Key_Tab = 280;
     * }
     */
    public static int eRENDERDOC_Key_Tab() {
        return (int)280L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_InputButton.eRENDERDOC_Key_PrtScrn = 281;
     * }
     */
    public static int eRENDERDOC_Key_PrtScrn() {
        return (int)281L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_InputButton.eRENDERDOC_Key_Pause = 282;
     * }
     */
    public static int eRENDERDOC_Key_Pause() {
        return (int)282L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_InputButton.eRENDERDOC_Key_Max = 283;
     * }
     */
    public static int eRENDERDOC_Key_Max() {
        return (int)283L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_OverlayBits.eRENDERDOC_Overlay_Enabled = 1;
     * }
     */
    public static int eRENDERDOC_Overlay_Enabled() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_OverlayBits.eRENDERDOC_Overlay_FrameRate = 2;
     * }
     */
    public static int eRENDERDOC_Overlay_FrameRate() {
        return (int)2L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_OverlayBits.eRENDERDOC_Overlay_FrameNumber = 4;
     * }
     */
    public static int eRENDERDOC_Overlay_FrameNumber() {
        return (int)4L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_OverlayBits.eRENDERDOC_Overlay_CaptureList = 8;
     * }
     */
    public static int eRENDERDOC_Overlay_CaptureList() {
        return (int)8L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_OverlayBits.eRENDERDOC_Overlay_Default = 15;
     * }
     */
    public static int eRENDERDOC_Overlay_Default() {
        return (int)15L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_OverlayBits.eRENDERDOC_Overlay_All = -1;
     * }
     */
    public static int eRENDERDOC_Overlay_All() {
        return (int)-1L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_OverlayBits.eRENDERDOC_Overlay_None = 0;
     * }
     */
    public static int eRENDERDOC_Overlay_None() {
        return (int)0L;
    }
    /**
     * {@snippet :
     * typedef void* RENDERDOC_DevicePointer;
     * }
     */
    public static final AddressLayout RENDERDOC_DevicePointer = RuntimeHelper.POINTER;
    /**
     * {@snippet :
     * typedef void* RENDERDOC_WindowHandle;
     * }
     */
    public static final AddressLayout RENDERDOC_WindowHandle = RuntimeHelper.POINTER;
    /**
     * {@snippet :
     * enum RENDERDOC_Version.eRENDERDOC_API_Version_1_0_0 = 10000;
     * }
     */
    public static int eRENDERDOC_API_Version_1_0_0() {
        return (int)10000L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_Version.eRENDERDOC_API_Version_1_0_1 = 10001;
     * }
     */
    public static int eRENDERDOC_API_Version_1_0_1() {
        return (int)10001L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_Version.eRENDERDOC_API_Version_1_0_2 = 10002;
     * }
     */
    public static int eRENDERDOC_API_Version_1_0_2() {
        return (int)10002L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_Version.eRENDERDOC_API_Version_1_1_0 = 10100;
     * }
     */
    public static int eRENDERDOC_API_Version_1_1_0() {
        return (int)10100L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_Version.eRENDERDOC_API_Version_1_1_1 = 10101;
     * }
     */
    public static int eRENDERDOC_API_Version_1_1_1() {
        return (int)10101L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_Version.eRENDERDOC_API_Version_1_1_2 = 10102;
     * }
     */
    public static int eRENDERDOC_API_Version_1_1_2() {
        return (int)10102L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_Version.eRENDERDOC_API_Version_1_2_0 = 10200;
     * }
     */
    public static int eRENDERDOC_API_Version_1_2_0() {
        return (int)10200L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_Version.eRENDERDOC_API_Version_1_3_0 = 10300;
     * }
     */
    public static int eRENDERDOC_API_Version_1_3_0() {
        return (int)10300L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_Version.eRENDERDOC_API_Version_1_4_0 = 10400;
     * }
     */
    public static int eRENDERDOC_API_Version_1_4_0() {
        return (int)10400L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_Version.eRENDERDOC_API_Version_1_4_1 = 10401;
     * }
     */
    public static int eRENDERDOC_API_Version_1_4_1() {
        return (int)10401L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_Version.eRENDERDOC_API_Version_1_4_2 = 10402;
     * }
     */
    public static int eRENDERDOC_API_Version_1_4_2() {
        return (int)10402L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_Version.eRENDERDOC_API_Version_1_5_0 = 10500;
     * }
     */
    public static int eRENDERDOC_API_Version_1_5_0() {
        return (int)10500L;
    }
    /**
     * {@snippet :
     * enum RENDERDOC_Version.eRENDERDOC_API_Version_1_6_0 = 10600;
     * }
     */
    public static int eRENDERDOC_API_Version_1_6_0() {
        return (int)10600L;
    }
    /**
     * {@snippet :
     * #define _POSIX_C_SOURCE 200809
     * }
     */
    public static long _POSIX_C_SOURCE() {
        return 200809L;
    }
    /**
     * {@snippet :
     * #define __TIMESIZE 64
     * }
     */
    public static int __TIMESIZE() {
        return (int)64L;
    }
    /**
     * {@snippet :
     * #define __STDC_IEC_60559_BFP__ 201404
     * }
     */
    public static long __STDC_IEC_60559_BFP__() {
        return 201404L;
    }
    /**
     * {@snippet :
     * #define __STDC_IEC_60559_COMPLEX__ 201404
     * }
     */
    public static long __STDC_IEC_60559_COMPLEX__() {
        return 201404L;
    }
    /**
     * {@snippet :
     * #define __STDC_ISO_10646__ 201706
     * }
     */
    public static long __STDC_ISO_10646__() {
        return 201706L;
    }
    /**
     * {@snippet :
     * #define __WCHAR_MAX 2147483647
     * }
     */
    public static int __WCHAR_MAX() {
        return (int)2147483647L;
    }
    /**
     * {@snippet :
     * #define __WCHAR_MIN -2147483648
     * }
     */
    public static int __WCHAR_MIN() {
        return (int)-2147483648L;
    }
    /**
     * {@snippet :
     * #define INT8_MIN -128
     * }
     */
    public static int INT8_MIN() {
        return (int)-128L;
    }
    /**
     * {@snippet :
     * #define INT16_MIN -32768
     * }
     */
    public static int INT16_MIN() {
        return (int)-32768L;
    }
    /**
     * {@snippet :
     * #define INT32_MIN -2147483648
     * }
     */
    public static int INT32_MIN() {
        return (int)-2147483648L;
    }
    /**
     * {@snippet :
     * #define INT64_MIN -9223372036854775808
     * }
     */
    public static long INT64_MIN() {
        return -9223372036854775808L;
    }
    /**
     * {@snippet :
     * #define INT8_MAX 127
     * }
     */
    public static int INT8_MAX() {
        return (int)127L;
    }
    /**
     * {@snippet :
     * #define INT16_MAX 32767
     * }
     */
    public static int INT16_MAX() {
        return (int)32767L;
    }
    /**
     * {@snippet :
     * #define INT32_MAX 2147483647
     * }
     */
    public static int INT32_MAX() {
        return (int)2147483647L;
    }
    /**
     * {@snippet :
     * #define INT64_MAX 9223372036854775807
     * }
     */
    public static long INT64_MAX() {
        return 9223372036854775807L;
    }
    /**
     * {@snippet :
     * #define UINT8_MAX 255
     * }
     */
    public static int UINT8_MAX() {
        return (int)255L;
    }
    /**
     * {@snippet :
     * #define UINT16_MAX 65535
     * }
     */
    public static int UINT16_MAX() {
        return (int)65535L;
    }
    /**
     * {@snippet :
     * #define UINT32_MAX 4294967295
     * }
     */
    public static int UINT32_MAX() {
        return (int)4294967295L;
    }
    /**
     * {@snippet :
     * #define UINT64_MAX -1
     * }
     */
    public static long UINT64_MAX() {
        return -1L;
    }
    /**
     * {@snippet :
     * #define INT_LEAST8_MIN -128
     * }
     */
    public static int INT_LEAST8_MIN() {
        return (int)-128L;
    }
    /**
     * {@snippet :
     * #define INT_LEAST16_MIN -32768
     * }
     */
    public static int INT_LEAST16_MIN() {
        return (int)-32768L;
    }
    /**
     * {@snippet :
     * #define INT_LEAST32_MIN -2147483648
     * }
     */
    public static int INT_LEAST32_MIN() {
        return (int)-2147483648L;
    }
    /**
     * {@snippet :
     * #define INT_LEAST64_MIN -9223372036854775808
     * }
     */
    public static long INT_LEAST64_MIN() {
        return -9223372036854775808L;
    }
    /**
     * {@snippet :
     * #define INT_LEAST8_MAX 127
     * }
     */
    public static int INT_LEAST8_MAX() {
        return (int)127L;
    }
    /**
     * {@snippet :
     * #define INT_LEAST16_MAX 32767
     * }
     */
    public static int INT_LEAST16_MAX() {
        return (int)32767L;
    }
    /**
     * {@snippet :
     * #define INT_LEAST32_MAX 2147483647
     * }
     */
    public static int INT_LEAST32_MAX() {
        return (int)2147483647L;
    }
    /**
     * {@snippet :
     * #define INT_LEAST64_MAX 9223372036854775807
     * }
     */
    public static long INT_LEAST64_MAX() {
        return 9223372036854775807L;
    }
    /**
     * {@snippet :
     * #define UINT_LEAST8_MAX 255
     * }
     */
    public static int UINT_LEAST8_MAX() {
        return (int)255L;
    }
    /**
     * {@snippet :
     * #define UINT_LEAST16_MAX 65535
     * }
     */
    public static int UINT_LEAST16_MAX() {
        return (int)65535L;
    }
    /**
     * {@snippet :
     * #define UINT_LEAST32_MAX 4294967295
     * }
     */
    public static int UINT_LEAST32_MAX() {
        return (int)4294967295L;
    }
    /**
     * {@snippet :
     * #define UINT_LEAST64_MAX -1
     * }
     */
    public static long UINT_LEAST64_MAX() {
        return -1L;
    }
    /**
     * {@snippet :
     * #define INT_FAST8_MIN -128
     * }
     */
    public static int INT_FAST8_MIN() {
        return (int)-128L;
    }
    /**
     * {@snippet :
     * #define INT_FAST16_MIN -9223372036854775808
     * }
     */
    public static long INT_FAST16_MIN() {
        return -9223372036854775808L;
    }
    /**
     * {@snippet :
     * #define INT_FAST32_MIN -9223372036854775808
     * }
     */
    public static long INT_FAST32_MIN() {
        return -9223372036854775808L;
    }
    /**
     * {@snippet :
     * #define INT_FAST64_MIN -9223372036854775808
     * }
     */
    public static long INT_FAST64_MIN() {
        return -9223372036854775808L;
    }
    /**
     * {@snippet :
     * #define INT_FAST8_MAX 127
     * }
     */
    public static int INT_FAST8_MAX() {
        return (int)127L;
    }
    /**
     * {@snippet :
     * #define INT_FAST16_MAX 9223372036854775807
     * }
     */
    public static long INT_FAST16_MAX() {
        return 9223372036854775807L;
    }
    /**
     * {@snippet :
     * #define INT_FAST32_MAX 9223372036854775807
     * }
     */
    public static long INT_FAST32_MAX() {
        return 9223372036854775807L;
    }
    /**
     * {@snippet :
     * #define INT_FAST64_MAX 9223372036854775807
     * }
     */
    public static long INT_FAST64_MAX() {
        return 9223372036854775807L;
    }
    /**
     * {@snippet :
     * #define UINT_FAST8_MAX 255
     * }
     */
    public static int UINT_FAST8_MAX() {
        return (int)255L;
    }
    /**
     * {@snippet :
     * #define UINT_FAST16_MAX -1
     * }
     */
    public static long UINT_FAST16_MAX() {
        return -1L;
    }
    /**
     * {@snippet :
     * #define UINT_FAST32_MAX -1
     * }
     */
    public static long UINT_FAST32_MAX() {
        return -1L;
    }
    /**
     * {@snippet :
     * #define UINT_FAST64_MAX -1
     * }
     */
    public static long UINT_FAST64_MAX() {
        return -1L;
    }
    /**
     * {@snippet :
     * #define INTPTR_MIN -9223372036854775808
     * }
     */
    public static long INTPTR_MIN() {
        return -9223372036854775808L;
    }
    /**
     * {@snippet :
     * #define INTPTR_MAX 9223372036854775807
     * }
     */
    public static long INTPTR_MAX() {
        return 9223372036854775807L;
    }
    /**
     * {@snippet :
     * #define UINTPTR_MAX -1
     * }
     */
    public static long UINTPTR_MAX() {
        return -1L;
    }
    /**
     * {@snippet :
     * #define INTMAX_MIN -9223372036854775808
     * }
     */
    public static long INTMAX_MIN() {
        return -9223372036854775808L;
    }
    /**
     * {@snippet :
     * #define INTMAX_MAX 9223372036854775807
     * }
     */
    public static long INTMAX_MAX() {
        return 9223372036854775807L;
    }
    /**
     * {@snippet :
     * #define UINTMAX_MAX -1
     * }
     */
    public static long UINTMAX_MAX() {
        return -1L;
    }
    /**
     * {@snippet :
     * #define PTRDIFF_MIN -9223372036854775808
     * }
     */
    public static long PTRDIFF_MIN() {
        return -9223372036854775808L;
    }
    /**
     * {@snippet :
     * #define PTRDIFF_MAX 9223372036854775807
     * }
     */
    public static long PTRDIFF_MAX() {
        return 9223372036854775807L;
    }
    /**
     * {@snippet :
     * #define SIG_ATOMIC_MIN -2147483648
     * }
     */
    public static int SIG_ATOMIC_MIN() {
        return (int)-2147483648L;
    }
    /**
     * {@snippet :
     * #define SIG_ATOMIC_MAX 2147483647
     * }
     */
    public static int SIG_ATOMIC_MAX() {
        return (int)2147483647L;
    }
    /**
     * {@snippet :
     * #define SIZE_MAX -1
     * }
     */
    public static long SIZE_MAX() {
        return -1L;
    }
    /**
     * {@snippet :
     * #define WCHAR_MIN -2147483648
     * }
     */
    public static int WCHAR_MIN() {
        return (int)-2147483648L;
    }
    /**
     * {@snippet :
     * #define WCHAR_MAX 2147483647
     * }
     */
    public static int WCHAR_MAX() {
        return (int)2147483647L;
    }
    /**
     * {@snippet :
     * #define WINT_MIN 0
     * }
     */
    public static int WINT_MIN() {
        return (int)0L;
    }
    /**
     * {@snippet :
     * #define WINT_MAX 4294967295
     * }
     */
    public static int WINT_MAX() {
        return (int)4294967295L;
    }
    /**
     * {@snippet :
     * #define RENDERDOC_ShaderDebugMagicValue_truncated 5216688378538513696
     * }
     */
    public static long RENDERDOC_ShaderDebugMagicValue_truncated() {
        return 5216688378538513696L;
    }
}


