// Generated by jextract

package net.renderdoc.api;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * typedef struct RENDERDOC_API_1_6_0 RENDERDOC_API_1_4_1;
 * }
 */
public final class RENDERDOC_API_1_4_1 extends RENDERDOC_API_1_6_0 {

    // Suppresses default constructor, ensuring non-instantiability.
    private RENDERDOC_API_1_4_1() {}
}


