// Generated by jextract

package net.renderdoc.api;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef RENDERDOC_API_1_6_0 RENDERDOC_API_1_1_1
 * }
 */
public class RENDERDOC_API_1_1_1 extends RENDERDOC_API_1_6_0 {

    RENDERDOC_API_1_1_1() {
        // Should not be called directly
    }
}

